name: Colonies
main: justinDevB.Colonies.Colonies
version: 0.0.1-SNAPSHOT
author: Justin
api-version: 1.15
commands:
  colonies:
    description: colonies base command
    aliases: [c]
  accept:
    description: Accept an invite to a Colony
  decline:
    description: Decline an invite to a Colony
